### ISSUE TITLE
Will not send Texts 

### ISSUE THREAD

**Issue by aberryt** [brismuth/google-voice-bulk-texter#13]
Hi, 

Just added the extension and went to test. I added 4 numbers to send a message to and hit the send message button. The app seemed to be trying to send to each one and was rotating through the numbers repeatedly. I let this go on for a couple of minutes before refreshing the page to see if any of the text messages had actually sent. Not really sure what I am doing wrong or if is and issue with the extension. Any direction would be greatly appreciated. 

Amanda

**Comment by aberryt** [comment]
Hi sorry for the slow reply. Yes the text feature works. I had a video but it is not letting me attach..

**Comment by brismuth** [comment]
No worries. Can you maybe try uploading it tov Google drive and sharing the link here? Thanks!

**Comment by aberryt** [comment]
Ah Great idea! here you go https://drive.google.com/open?id=1OY9_unEeWgbotpYPf5TGA5MHk0aUS9Tt

**Comment by brismuth** [comment]
I clicked the link and requested access with my account. You should have an email prompting you to grant access.

**Comment by brismuth** [comment]
Thanks for recording that! That's super helpful. I think I see what's going on.

All your phone numbers begin with the a "1" prefix (the US country code). Google Voice is stripping that off when you enter the chat window, which causes my extension to think that the numbers don't match. Because of that, the extension starts over. I added a lot of safeguards to prevent the extension from ever sending a message to the wrong number. 🙂

I'll update the extension to handle this, but in the meantime if you remove those "1"s that should fix it for you.

**Comment by aberryt** [comment]
ok cool. It looks like it is working! Woo! thanks for your time toward this. Appreciated! 

Amanda

**Comment by brismuth** [comment]
In the latest version (1.0.0), the extension will now automatically remove the US country code if it's present to prevent the issue you ran into.

If you want to thank me, you can leave a review on the extension page. :) 
https://chrome.google.com/webstore/detail/google-voice-bulk-texter/gdplkhplnfgmodalfimcondhmokmekka

**Comment by brismuth** [comment]
@Qxboxone I see you opened a separate issue for this (#19) and it appears you figured out the problem. I'm going to leave this issue closed.
