### ISSUE TITLE
Google Voice Bulk Texter Not Working

### ISSUE THREAD

**Issue by jtobin875** [brismuth/google-voice-bulk-texter#162]
Hi GitHub! 

I am trying to use the google voice bulk texter but when I try to send a bulk text, the message won't go through (the message box is empty). I have tried limiting the quantity of numbers I am texting (even to <10 phone numbers), adjusting the delay time in between each text and deleting/redownloading google voice bulk texter. However, none of these have worked. I am currently using a mac laptop and would appreciate any tips or suggestions on how to get the bulk texter to work. Thank you so much!

**Comment by brismuth** [comment]
I’d recommend starting with a simple message - like sending “Hello” to your own phone number. If the message box isn’t being filled, maybe there’s a symbol or emoji or something in the message that’s causing that part to crash?
Are you getting any error messages?

**Comment by jtobin875** [comment]
Thank you for your response!! I am able to send a simple message to my own phone number. It's when I involve more than 1 number that the message won't go through. I don't get any error messages, I just see the first phone number being typed and then no message is written or sent. It pauses after inputting the phone number

**Comment by Any0930** [comment]
I'm currently having the same problem as you!

**Comment by brismuth** [comment]
Actually, I think this issue is separate from #169 - but try v1.3.3 just in case and let me know if it resolves the issue.

Follow the instructions here to update to v1.3.3:
https://github.com/brismuth/google-voice-bulk-texter#update-it

Per the [support page](https://github.com/brismuth/google-voice-bulk-texter/blob/master/support.md#extension-is-looping-on-a-single-number-and-failing-with-an-error-message):
> **Extension is looping on a single number and failing with an error message**
> This is usually caused by Google Voice rolling out website changes in phases. 

That is why issues typically affect a small group of people first, and gradually affected more people. Unfortunately, it's not affecting my account, so I am unable to test a fix myself.

**Comment by jackpot08** [comment]
> 

hi Brian. thanks for chimming in. Is there a certain browser you recommend (firefox, chrome, edge). i am getting this issue but want the issue of it being stuck.

thanks so much

**Comment by brismuth** [comment]
Is this issue still affecting you? 

Sorry about not responding before - I recommend Firefox since it supports automatic updates, but am in the process of rolling out support for Edge as well.

**Comment by jbunch7** [comment]
This issue is still occurring. Im on chrome, launched my first bulk text and it rolled through about 20 texts before breaking. Now it continues to type out the same number without sending the text
