### ISSUE TITLE
Bulk Texter Will only send 1 text then an error pops up.

### ISSUE THREAD

**Issue by Bprince18** [brismuth/google-voice-bulk-texter#204]
**Describe the bug**
Google Voice bulk texter v2.0.5:
Text failed. You can find support resources by opening Google Voice Bulk Texter popup and clicking "Get Help" at the bottom.

error: "confirm sent" failed

**URL**
The URL you were on when the problem occurred. 

**Expected behavior**
Normally the text is confirmed and it automatically moves to the next number

**Screenshots**

**Additional context**

**Comment by NiallJohnson** [comment]
Also having this issue!

Describe the bug:
Google Voice bulk texter v2.0.5: - Firefox Extension
Text failed. You can find support resources by opening Google Voice Bulk Texter popup and clicking "Get Help" at the bottom.

error: "confirm sent" failed 

URL
https://voice.google.com/u/0/messages?itemId=draft-AC12669B-B759-48DE-B515-9EEBBEACB933

Expected behavior
Normally the text is confirmed and it automatically moves to the next number - it puts the number and name in but it doesn't send. It keeps trying to send but it never goes out.

Screenshots
![image](https://user-images.githubusercontent.com/100169708/197025058-6bf76bd1-209a-4a1b-a6d1-ca2992d773e3.png)

Additional context
Was working fine earlier! Then stopped with that error: "confirm sent" failed

**Comment by brismuth** [comment]
Let's track this on issue #194 - feel free to comment on that thread.
