### ISSUE TITLE
Bulk Texter not sending the messages at all 

### ISSUE THREAD

**Issue by AndreaSoliz** [brismuth/google-voice-bulk-texter#48]
**Describe the bug**
I have inserted my message, as well as, the numbers I want to send it out too.   The bulk texter begins normally, inserts the number, inserts the message;however, it doesn't "press" the send button. So it wont sent anything.  :( 

**URL**
The URL you were on when the problem occurred. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by brismuth** [comment]
Did this issue suddenly start occurring for you? 

Has the extension worked for you successfully in the past?

Can you try sending a simple "test" text message to your own phone number?

**Comment by brismuth** [comment]
@jenablue @stride76 can you answer the same questions regarding your experience?

1. Did this issue suddenly start occurring for you?
2. Has the extension worked for you successfully in the past?
3. Can you try sending a simple "test" text message to your own phone number?

**Comment by AndreaSoliz** [comment]
https://drive.google.com/file/d/1u83TzxPOYc3cDj9I_sFEijyDIX_Ut9bE/view

Here is the link to it on my googledrive, I'm not sure if the video was
successfully delivered

**Comment by ernmcbaldwin** [comment]
Describe the bug
I have inserted my message, as well as, the numbers I want to send it out too=. The bulk texter begins normally, inserts the number, inserts the message;however, it doesn't "press" the send button. So it wont sent anything. 

URL
https://voice.google.com/u/0/messages?itemId=draft-2EF5E64A-2774-4726-BD93-BED135C02933

Expected behavior
I expected texts to be sent the each of the numbers I put in the bulk texter

![Bulk texter 2](https://user-images.githubusercontent.com/49159475/55335417-0a24e480-5469-11e9-9e46-1ce838201daf.jpg)
![bulk texter](https://user-images.githubusercontent.com/49159475/55335419-0a24e480-5469-11e9-8713-acedd6c75aa8.jpg)

**Comment by ernmcbaldwin** [comment]
I just downloaded the extension today; it has not worked for me correctly yet.
I tried one text to myself; that is when I discovered the problem.

**Comment by brismuth** [comment]
It seems likely that Google is rolling out an update to their interface that breaks the extension’s ability to press the send button. I’m on vacation right now though and won’t have access to my laptop to update the extension until Thursday. 

If anyone else runs into this issue, feel free to hit the “Subscribe” button on the right side of this page. That way you’ll get an email once I’ve updated the extension to handle this issue.

**Comment by jenablue** [comment]
Yes that is the same thing that happens to me. Great I will wait for your email for update. Thank you!!!

**Comment by Shahids2000** [comment]
Same thing
I have inserted my message, as well as, the numbers I want to send it out too. The bulk texter begins normally, inserts the number, inserts the message; however, it doesn't **press** the send button. So it wont sent anything.

**Comment by doodlez24** [comment]
![image](https://user-images.githubusercontent.com/36531750/55379327-91a63e00-54d1-11e9-8dda-f8c631c3c03c.png)

**Comment by amielech** [comment]
I am getting the same error message as doodlez24. Extension is not working.

**Comment by timothylittleton** [comment]
Same message...would be better if this was brought to my attention an hour into trying different methods....sorry for my rant

**Comment by Arkansaw1983** [comment]
Same not working......  Sam exact issue described above.   I had to hit the Send arrow for EACH message after it auto populated.

**Comment by tschurm** [comment]
Hi Brismuth!  Thank you for addressing this ongoing issue while on vacation and we look forward to your update upon your return!

**Comment by karloslharris** [comment]
Hello Brismuth!  Just wanted to chime in as I too have been experiencing the same issue stated above.  Plain and simple: Thank you.  The extension is NOW perfect!  You sir are a genius!  Recently, there was a proposal made in the United States Senate which would update the Telephone Consumers Protection Act (TCPA) in such a way that use of your Bulk Texter would be considered illegal. (Of course depending upon how one uses it.)  Now, however, having to manually click the send button after each text loads is well within the parameters of the new proposal.  The name of the law is the Stop Bad Robocalls Act and for those who would like to read it, click here: 

https://www.congress.gov/bill/116th-congress/house-bill/946/text?q=%7B%22search%22%3A%5B%22Stopping+Bad+Robocalls%22%5D%7D&r=1&s=1

The fact that one has to manually send each text is a great thing.   But understanding the ills of everyone else here in need of automation, it would be great if we could somehow have both.  Cheers. :)

**Comment by ch0yer** [comment]
Any update on this?

**Comment by brismuth** [comment]
I confirmed that this was caused by a change on Google Voice's side.

I've just pushed the update to handle the change to the Chrome Web Store (the extension is now v1.1.3). It can take up to 60 minutes to become available there, and it can take longer than that to actually show up on your computer unless you force it to update.

Once you see 1.1.3 available at this link (https://chrome.google.com/webstore/detail/google-voice-bulk-texter/gdplkhplnfgmodalfimcondhmokmekka), you can force Chrome to update the extension by simply uninstalling and reinstalling it.

If you wish to support my development/maintenance efforts, feel free to [donate or leave a review](https://github.com/brismuth/google-voice-bulk-texter/blob/master/support.md#donating).
