### ISSUE TITLE
Copy and Paste function working but not sending

### ISSUE THREAD

**Issue by jaide1935** [brismuth/google-voice-bulk-texter#52]
**Describe the bug**
Number being copied and message being pasted but it will not send the message at all. Tried uninstalling and reinstalling extension. Sent from Google voice and it works. Just not working through the extension! Need help ASAP as i rely on this for work. 

Thank you

**URL**
The URL you were on when the problem occurred. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by brismuth** [comment]
See issue #48.

**Comment by jaide1935** [comment]
I did but i dont understand how to fix it

**Comment by brismuth** [comment]
This issue you created is a duplicate of that issue. Since you didn't read through the thread that I linked I'll repost my comment here for you.

>>> It seems likely that Google is rolling out an update to their interface that breaks the extension’s ability to press the send button. I’m on vacation right now though and won’t have access to my laptop to update the extension until Thursday.

Feel free to hit the “Subscribe” button on the right side of that page (issue #48). That way you’ll get an email once I’ve updated the extension to handle the issue.
