### ISSUE TITLE
Support custom intervals between sends

### ISSUE THREAD

**Issue by EdWood110** [brismuth/google-voice-bulk-texter#54]
Hi, 

This is a feature request that would make sense for us.

First, we would love to be able to attached a picture to the message.

Second, sending out text in intervals would be great. Like 25 messages every 15 minutes, etc.

Thank you.

**Comment by brismuth** [comment]
Attaching a picture won't be possible based on how the Google Voice application handles pictures, from what I've seen. 

Your other request would probably require adding some kind of interface that shows up on the Google Voice page as it's sending in order to not be confusing to users. I'm not opposed but I probably won't get around to it any time soon.

**Comment by EdWood110** [comment]
Thank you for your quick feedback on this. Much appreciated! :)

**Comment by brismuth** [comment]
I've added support for custom delays in the latest version of the extension! 

You can update to version 1.3.1 by following these instructions:
https://github.com/brismuth/google-voice-bulk-texter#update-it
