### ISSUE TITLE
How do we stay in compliance (are we violating Google's Acceptable Use Policy)?

### ISSUE THREAD

**Issue by jodyheath** [brismuth/google-voice-bulk-texter#57]
I love this plugin. And thanks for the expedient 1.1.3 update/fix (@brismuth). 

In reviewing googles **[Acceptable Use Policy](https://support.google.com/voice/answer/9230450?hl=en&ref_topic=9273222)**, however, it raised some questions about these two lines of their policy:
 
•  sending commercial or promotional messages to a large number of users, or **sending messages in bulk**;
•  sending messages via an **automated process, such as a script**;
 
Google allow’s the plugin in the Chrome store; yet, this plugin's purpose seems to violate some of their policy in terms, i.e.:

1) don’t we use this plugin to send messages in **bulk** (although this could just be ambiguous writing from Google's legal dept and they are only referring to commercial messages)?

2)  isn’t it a **script**?

I would love to hear anyone else’s take on this.
 
And don’t get me wrong. I’m certainly not a whistle blower. I’m just looking for a way to use this plugin as long as we can without having the plugin or our accounts banned.

Best,
 
 
--Jody

**Comment by brismuth** [comment]
Those are all good questions, and I don't know the answers to all of them. I'm not a lawyer, and I don't have any affiliation with Google. 

My guess is that some uses of the extension would not be concerning to Google (sending to friends, family, church group, etc), although they are technically in violation of the Acceptable Use Policy (usage of a script). Some other uses of the extension for which I'd expect them to be more likely to exercise the Acceptable Use Policy and deactivate the account would include marketing, spamming, or phishing, etc. 

I decided to put in the checkbox for the Acceptable Use Policy yesterday because I only found the policy yesterday. I had to Google it - I have no idea how to get to the policy from the actual Google Voice site. 🙂 A couple people have reported that their accounts were deactivated (at least temporarily) over the last year, so I wanted to make sure that users know the risk.

**Comment by jodyheath** [comment]
Great idea on the policy addition link. I haven't experienced any formal bans, personally. I use this to communicate with my work-place lotto pool.  I send ~ 50 bulk/mass messages 4 times per week. I always include an SSL link in every message.
 
While I haven't experienced any formal bans or received any notifications from Google of any violations, I have experienced temporary ghosting.  I.e., sometimes, after sending out 50 or so messages--if I attempt to send another mass text the same day--those latter messages are ghosted for up to ~ 24 hours (in other words, they will appear to be sent but won't actually be sent, ever).  But if I give it about a day, I'm back in business. 
 
I've learned to include my own non-google voice number (as the last recipient) in mass text, for a good indicator if the preceding messages are being received or not. I have also found that including emojis or non-SSL links tend to cause ghosting as well. 

Best!
